### PR TITLE
Ability to disable Cyrillic and other non Latin characters in C syntax

### PR DESCRIPTION
**Pull request by kant2002**
Also add same tests for Regex lexer.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
To be honest, I would vote against this. C standard allows the implementations to accept additional characters outside of basic ANSI letters, so this implementation is
a. Perfectly valid according to the modern standard's letter
b. Useable
c. I would even say "expected" of a modern programming language

**Comment by LPeter1997** [comment]
Having an option to enable/disable this is not unreasonable. If we had a flag to disable non-ASCII characters, I'd accept this. I believe the default should just accept any character-set, as most implementations that I know of also have no problem with this.

**Comment by kant2002** [comment]
What should I do to please SonarCube?

**Comment by LPeter1997** [comment]
@kant2002 Don't worry about Sonar, it will be turned off soon as it causes more pain than help. Thank you so much for the contribution!

**Pull request merged**
